version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - sictel_net
    volumes:
      - ./data:/var/www/html/data

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sictel
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - sictel_net

networks:
  sictel_net:

volumes:
  db_data:
